
export const LatestListingCardDets = [
    {
      url: '/images/1.jpg',
      purpose: 'For Rent',
      location: 'Bhopal',
      price: 90,
      text: 'Luxury Vila in Rego Park',
      Number_of_bedroom: 3,
      Number_of_bathroom: 3,
      owner_name: 'Sujal',
      isRent : true ,
    },
    {
      url: '/images/7.jpg',
      purpose: 'For Sale',
      location: 'Indore',
      price: 100,
      text: 'Appartment in Mumbai',
      Number_of_bedroom: 2,
      Number_of_bathroom: 2,
      owner_name: 'Rohan',
      isRent : false ,
    },
    {
      url: '/images/3.jpg',
      purpose: 'For Rent',
      location: 'Bhopal',
      price: 90,
      text: 'Luxury Vila in Rego Park',
      Number_of_bedroom: 3,
      Number_of_bathroom: 3,
      owner_name: 'Sujal',
      isRent : true ,
    },
    {
      url: '/images/5.jpg',
      purpose: 'For Sale',
      location: 'Indore',
      price: 100,
      text: 'Appartment in Mumbai',
      Number_of_bedroom: 2,
      Number_of_bathroom: 2,
      owner_name: 'Rohan',
      isRent : false ,
    },
    {
      url: '/images/6.jpg',
      purpose: 'For Sale',
      location: 'Indore',
      price: 100,
      text: 'Appartment in Mumbai',
      Number_of_bedroom: 2,
      Number_of_bathroom: 2,
      owner_name: 'Rohan',
      isRent : false ,
    },
    {
      url: '/images/1.jpg',
      purpose: 'For Rent',
      location: 'Indore',
      price: 100,
      text: 'Appartment in Mumbai',
      Number_of_bedroom: 2,
      Number_of_bathroom: 2,
      owner_name: 'Rohan',
      isRent : true ,
    },
    
    // Add more card data as needed
  ];
  